platform :ios, '13.0'
use_frameworks!
install! 'cocoapods',
:disable_input_output_paths => true,
:share_schemes_for_development_pods => true

target 'EachNavigationBar_Example' do
  pod 'EachNavigationBar', :path => '../'

  target 'EachNavigationBar_Tests' do
    inherit! :search_paths

  end
end
